mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'puppetlabs-puppetdb', '7.1.0'
mod 'puppetlabs/firewall'
mod 'puppetlabs/inifile'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/postgresql'
